-- MySQL Script generated by MySQL Workbench
-- 08/06/15 21:03:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema matricula
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema matricula
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `matricula` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `matricula` ;

-- -----------------------------------------------------
-- Tabela `matricula`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matricula`.`Aluno` (
  `ra` INT NOT NULL COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(60) NOT NULL COMMENT '',
  `senha` VARCHAR(64) NOT NULL COMMENT '',
  `turno` VARCHAR(10) NULL COMMENT '',
  `cr` FLOAT NULL COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '',
  PRIMARY KEY (`ra`)  COMMENT '',
  UNIQUE INDEX `ra_UNIQUE` (`ra` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Tabela `matricula`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matricula`.`Curso` (
  `idCurso` INT NOT NULL COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idCurso`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Tabela `matricula`.`Coordenador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matricula`.`Coordenador` (
  `idCoordenador` INT NOT NULL COMMENT '',
  `email` VARCHAR(60) NULL COMMENT '',
  `senha` VARCHAR(64) NOT NULL COMMENT '',
  PRIMARY KEY (`idCoordenador`)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Tabela `matricula`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matricula`.`Disciplina` (
  `idDisciplina` VARCHAR(7) NOT NULL COMMENT '',
  `nome` VARCHAR(45) NULL COMMENT '',
  `t` TINYINT(2) NULL COMMENT '',
  `p` TINYINT(2) NULL COMMENT '',
  `i` TINYINT(2) NULL COMMENT '',
  `Coordenador_idCoordenador` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idDisciplina`)  COMMENT '',
  INDEX `fk_Disciplina_Coordenador1_idx` (`Coordenador_idCoordenador` ASC)  COMMENT '',
  CONSTRAINT `fk_Disciplina_Coordenador1`
    FOREIGN KEY (`Coordenador_idCoordenador`)
    REFERENCES `matricula`.`Coordenador` (`idCoordenador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Tabela `matricula`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matricula`.`Turma` (
  `idTurma` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `codigo` VARCHAR(16) NOT NULL COMMENT '',
  `quadrimestre` CHAR(6) NOT NULL COMMENT '',
  `vagas` INT NOT NULL COMMENT '',
  `Coordenador_idCoordenador` INT NOT NULL COMMENT '',
  `Disciplina_idDisciplina` VARCHAR(7) NOT NULL COMMENT '',
  PRIMARY KEY (`idTurma`)  COMMENT '',
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC)  COMMENT '',
  INDEX `fk_Turma_Coordenador1_idx` (`Coordenador_idCoordenador` ASC)  COMMENT '',
  INDEX `fk_Turma_Disciplina1_idx` (`Disciplina_idDisciplina` ASC)  COMMENT '',
  CONSTRAINT `fk_Turma_Coordenador1`
    FOREIGN KEY (`Coordenador_idCoordenador`)
    REFERENCES `matricula`.`Coordenador` (`idCoordenador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turma_Disciplina1`
    FOREIGN KEY (`Disciplina_idDisciplina`)
    REFERENCES `matricula`.`Disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Tabela `matricula`.`Docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matricula`.`Docente` (
  `siape` INT NOT NULL COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`siape`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Tabela `matricula`.`Aluno_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matricula`.`Aluno_curso` (
  `Aluno_ra` INT NOT NULL COMMENT '',
  `Curso_idCurso` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Aluno_ra`, `Curso_idCurso`)  COMMENT '',
  INDEX `fk_Curso_has_Aluno_Aluno1_idx` (`Aluno_ra` ASC)  COMMENT '',
  INDEX `fk_Curso_has_Aluno_Curso1_idx` (`Curso_idCurso` ASC)  COMMENT '',
  CONSTRAINT `fk_Curso_has_Aluno_Curso1`
    FOREIGN KEY (`Curso_idCurso`)
    REFERENCES `matricula`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Curso_has_Aluno_Aluno1`
    FOREIGN KEY (`Aluno_ra`)
    REFERENCES `matricula`.`Aluno` (`ra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Tabela `matricula`.`Aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matricula`.`Aula` (
  `idAula` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `dia_semana` VARCHAR(20) NOT NULL COMMENT '',
  `inicio` INT NOT NULL COMMENT '',
  `fim` INT NOT NULL COMMENT '',
  `sala` VARCHAR(10) NOT NULL COMMENT '',
  `tipo` VARCHAR(7) NOT NULL COMMENT '',
  `campus` VARCHAR(24) NOT NULL COMMENT '',
  `Turma_idTurma` INT NOT NULL COMMENT '',
  `Docente_siape` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idAula`, `Turma_idTurma`, `Docente_siape`)  COMMENT '',
  INDEX `fk_Turma_has_Docente_Docente1_idx` (`Docente_siape` ASC)  COMMENT '',
  INDEX `fk_Turma_has_Docente_Turma1_idx` (`Turma_idTurma` ASC)  COMMENT '',
  CONSTRAINT `fk_Turma_has_Docente_Turma1`
    FOREIGN KEY (`Turma_idTurma`)
    REFERENCES `matricula`.`Turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turma_has_Docente_Docente1`
    FOREIGN KEY (`Docente_siape`)
    REFERENCES `matricula`.`Docente` (`siape`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Tabela `matricula`.`Aluno_Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matricula`.`Aluno_Turma` (
  `Aluno_ra` INT NOT NULL COMMENT '',
  `Turma_idTurma` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Aluno_ra`, `Turma_idTurma`)  COMMENT '',
  INDEX `fk_Turma_has_Aluno_Aluno1_idx` (`Aluno_ra` ASC)  COMMENT '',
  INDEX `fk_Turma_has_Aluno_Turma1_idx` (`Turma_idTurma` ASC)  COMMENT '',
  CONSTRAINT `fk_Turma_has_Aluno_Turma1`
    FOREIGN KEY (`Turma_idTurma`)
    REFERENCES `matricula`.`Turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turma_has_Aluno_Aluno1`
    FOREIGN KEY (`Aluno_ra`)
    REFERENCES `matricula`.`Aluno` (`ra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
